### ISSUE TITLE
Changeset doesn't consider existing data 

### ISSUE THREAD

**Issue by bducharme** [mathieuprog/polymorphic_embed#10]
Hello!

In your documentation, one of the feature is the ability to add a changeset

> Run changeset validations when a changeset/2 function is present (when absent, the library will introspect the fields to cast)

What I found is that the first parameter is always an empty struct and not the actual existing data. Meaning that even if I do not cast some field, it will be reset to `nil` because of the data.

Is there something I do wrong or a known workaround? Is it known and _as designed_? 

Thank you!

Here's a simple example,

```
  schema "parent" do
    field(:child, Child)
  end

  def changeset(parent, attrs) do
    cast(parent, attrs, ~w(child)a)
  end
```

```
  embedded_schema "custom_child" do
    field(:first, :string)
    field(:second, :string)
  end

  def changeset(child, attrs) do
    cast(child, attrs, ~w(first)a)
  end
```

In this case, even if my existing child has a value for `second`, it won't be kept, unless I pass as `attrs` and cast it

**Comment by mathieuprog** [comment]
> What I found is that the first parameter is always an empty struct and not the actual existing data. Meaning that even if I do not cast some field, it will be reset to nil because of the data.

I don't see how the first parameter is an empty struct. See here the code that checks for a `changeset/2` function:
https://github.com/mathieuprog/polymorphic_embed/blob/v0.7.0/lib/polymorphic_embed/custom_type.ex#L90

Maybe you can add some logs and run `deps.compile` and see what happens?

Even better, create a failing test in the library's tests?

**Comment by mathieuprog** [comment]
See this test:
https://github.com/mathieuprog/polymorphic_embed/blob/master/test/polymorphic_embed_test.exs#L116

**Comment by bducharme** [comment]
By building on this test, if I do 

```
  test "update part of embed" do
    reminder = %Reminder{
      date: ~U[2020-05-28 02:57:19Z],
      text: "This is an SMS reminder",
      channel: %SMS{
        provider: %TwilioSMSProvider{
          api_key: "foo"
        },
        number: "02/807.05.53",
        result: %SMSResult{success: true},
        attempts: [
          %SMSAttempts{
            date: ~U[2020-05-28 07:27:05Z],
            result: %SMSResult{success: true}
          },
          %SMSAttempts{
            date: ~U[2020-05-28 07:27:05Z],
            result: %SMSResult{success: true}
          }
        ]
      }
    }

    reminder
    |> Reminder.changeset(%{})
    |> Repo.insert()

    reminder =
      Reminder
      |> QueryBuilder.where(text: "This is an SMS reminder")
      |> Repo.one()

    reminder
      |> Reminder.changeset(%{channel: %{
        __type__: "sms",
        number: "54"
      }})
      |> Repo.update()

    reminder =
      Reminder
      |> QueryBuilder.where(text: "This is an SMS reminder")
      |> Repo.one()

    assert reminder.channel.result.success
  end
```

This will fail since `result` is now `nil`

**Comment by bducharme** [comment]
As a work around, I have a function that convert the polymorphic embed to a map and then I update this one with my changes and pass it all as the "new" attributes. I don't have much time to get really into it sadly, but I'll keep an eye for any new development on this matter! Thanks!

**Comment by mathieuprog** [comment]
Could you try with version 0.9.0? Ecto must be >3.5.

See new example in the docs because API has changed:

1. specify options directly on the field in the schema (no more intermediary module)
2. use `cast_polymorphic_embed/2`

**Comment by bducharme** [comment]
I cannot make the switch as of now, but looking at the Pull Request, this should fix this use case. Feel free to close and thank you for the responsiveness!
