### ISSUE TITLE
module PolymorphicEmbed.HTML.Component is not loaded and could not be found

### ISSUE THREAD

**Issue by rubynho** [mathieuprog/polymorphic_embed#102]
I can't find a way to use the Component or Form modules, it seems to not be compiled. I tried importing the module as [the doc says](https://hexdocs.pm/polymorphic_embed/readme.html#displaying-form-inputs-and-errors-in-phoenix-templates), even in  `lib/shop_web/components/core_components.ex`, but raises the message below:
```
error: module PolymorphicEmbed.HTML.Component is not loaded and could not be found. This may be happening because the m
odule you are trying to load directly or indirectly depends on the current module
```

PolymorphicEmbed.HTML.Helpers seems to be compiled:
```elixir
iex(1)> Code.ensure_loaded? PolymorphicEmbed.HTML.Form
false
iex(2)> Code.ensure_loaded? PolymorphicEmbed.HTML.Component
false
iex(3)> Code.ensure_loaded? PolymorphicEmbed.HTML.Helpers
true
```

Elixir version: 1.16.1 (compiled with Erlang/OTP 26)
Phoenix version: 1.7.12
Polymorphic Embed version: 4.0.0

**Comment by mathieuprog** [comment]
@SteffenDE could you have a quick look at this? 🙏🏻

**Comment by SteffenDE** [comment]
@mathieuprog You didn’t make a new release since https://github.com/mathieuprog/polymorphic_embed/pull/97, right? So my quick guess is that it’s this.

**Comment by mathieuprog** [comment]
Actually I did. @rubynho you're not on the latest version.

**Comment by rubynho** [comment]
Great, that works. Thanks! The version spec in the documentation could be `"~> 4.0"` to allow minor version updates.

**Comment by mathieuprog** [comment]
Okay done: https://github.com/mathieuprog/polymorphic_embed/tree/master?tab=readme-ov-file#installation
👍

**Comment by xantrac** [comment]
Hello, I'm still getting this error even I'm on v.5.0.0 same using the git branch directly 

```
 {:polymorphic_embed, "~> 5.0"}


 {:polymorphic_embed,
       git: "https://github.com/mathieuprog/polymorphic_embed.git", tag: "v5.0.0"}
```


```
iex(2)> Code.ensure_loaded? PolymorphicEmbed.HTML.Form
false
```

**Comment by SteffenDE** [comment]
@xantrac it is only available if this check succeeds at compile time:

```elixir
if Code.ensure_loaded?(Phoenix.HTML) && Code.ensure_loaded?(Phoenix.HTML.Form) && Code.ensure_loaded?(PhoenixHTMLHelpers.Form) do
```

Do you have `:phoenix_html` (>= 4.0) and `:phoenix_html_helpers` in your dependencies?

**Comment by xantrac** [comment]
I was looking at that right now,

I don't have `PhoenixHTMLHelpers.Form` since it was deprecates in favor of `Phoenix.Component` https://hexdocs.pm/phoenix_html_helpers/PhoenixHTMLHelpers.html

**Comment by xantrac** [comment]
I don't know how I couldn't see it. Thank you. FWIW https://hexdocs.pm/phoenix_html/3.2.0/Phoenix.HTML.Form.html#hidden_inputs_for/1 is available in PHoenix.HTML as well. Not sure if you would compatibility issues with older phoenix versions.
