### ISSUE TITLE
Question on DB schemas

### ISSUE THREAD

**Issue by MichaelSwartz** [mathieuprog/polymorphic_embed#11]
Hi Mathieu,

Thanks for creating this library, it's a great contribution! I have a few questions about the recommended way to store records with schemas that use this library in a database.
- Would all fields from all embedded schemas (in one standard schema) be included in one table? So using your example from the readme, would the migration look like the following?

```
create table(:reminders) do
  add :date, :utc_datetime
  add :text, :string
  add :address, :string
  add :confirmed, :boolean
  add :number, :string
  ...
```
- Would you add a string field for the `channel`?
- If a field is shared by, for example, 2 of three of the options for an embedded schema, is it ok to share the column? 

Thanks! I'm fairly new to Elixir/Ecto, so maybe these question doesn't need to be answered for most users. If they do, I'd happy to make a PR to add explanation based on your answers to the docs.

**Comment by MichaelSwartz** [comment]
Hi again,

After reading more about regular embeds I see that this probably just uses a single map field. Sorry for the bother! Thanks

**Comment by mathieuprog** [comment]
Welcome to Elixir:)

Indeed it's just a `:map` field in the migration. You can also have an array of maps, which I still need to document.

In postgresql this will translate into a jsonb column.

**Comment by MichaelSwartz** [comment]
Thanks! Great
