### ISSUE TITLE
Using a factory library to seed schema fails when polymorphic field is nil

### ISSUE THREAD

**Issue by gcauchon** [mathieuprog/polymorphic_embed#15]
We are using `ex_machina` to seed schema and data in our tests. However, when trying to seed a schema with a `nil` polymorphic field, we face the following error:

> `(UndefinedFunctionError) function nil.__struct__/0 is undefined. If you are using the dot syntax, such as map.field or module.function, make sure the left side of the dot is an atom or a map`

ExMachina uses `cast/2`, which never pattern match on a `nil` value. I forked the library to provide reproduction steps in a separate codebase not to include an additional dependency here!

```
> mix test test/polymorphic_embed_test.exs:114
…

  1) test inserting a null embed in ExMachina factory (PolymorphicEmbedTest)
     test/polymorphic_embed_test.exs:114
     ** (UndefinedFunctionError) function nil.__struct__/0 is undefined. If you are using the dot syntax, such as map.field or module.function, make sure the left side of the dot is an atom or a map
     code: Factory.insert(
     stacktrace:
       nil.__struct__()
       (elixir 1.10.4) lib/kernel.ex:2182: Kernel.struct/3
       (polymorphic_embed 0.12.0) lib/polymorphic_embed.ex:90: PolymorphicEmbed.cast_to_changeset/2
       (polymorphic_embed 0.12.0) lib/polymorphic_embed.ex:68: PolymorphicEmbed.cast/2
       (ex_machina 2.4.0) lib/ex_machina/ecto_strategy.ex:62: ExMachina.EctoStrategy.cast_value/3
       (ex_machina 2.4.0) lib/ex_machina/ecto_strategy.ex:48: anonymous fn/2 in ExMachina.EctoStrategy.cast_all_fields/1
       (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ex_machina 2.4.0) lib/ex_machina/ecto_strategy.ex:39: ExMachina.EctoStrategy.cast/1
       (ex_machina 2.4.0) lib/ex_machina/ecto_strategy.ex:25: ExMachina.EctoStrategy.handle_insert/2
       test/polymorphic_embed_test.exs:116: (test)

Finished in 0.4 seconds
14 tests, 1 failure, 13 excluded
```

**Comment by mathieuprog** [comment]
Thank you for adding the test ✌

The fix is available in release 0.13

**Comment by gcauchon** [comment]
That was fast! So fast I haven't had time to push the second commit with a little cleanup and the missing `cast/2` pattern match… 🍻

**Comment by mathieuprog** [comment]
Too fast actually 😁 Eventually I removed the `ex_machina` dependency, and made a more simple test that simulates exactly how `ex_machina` is casting a `nil` value of a custom type:

```
test "simulate ExMachina's cast for nil value" do
  assert {:ok, nil} = Ecto.Type.cast({:parameterized, PolymorphicEmbed, %{metadata: []}}, nil)
end
```

Having `ex_machina` as a dependency will confuse contributors, and quite some code can be removed.

🍻

**Comment by mathieuprog** [comment]
Also have a look at this tweet: https://twitter.com/davydog187/status/1274018846949736448

Ecto factories: https://hexdocs.pm/ecto/test-factories.html

**Comment by gcauchon** [comment]
> Too fast actually 😁 Eventually I removed the `ex_machina` dependency, and made a more simple test that simulates exactly how `ex_machina` is casting a `nil` value of a custom type:
> 
> 
> 
> ```
> 
> test "simulate ExMachina's cast for nil value" do
> 
>   assert {:ok, nil} = Ecto.Type.cast({:parameterized, PolymorphicEmbed, %{metadata: []}}, nil)
> 
> end
> 
> ```
> 
> 
> 
> Having `ex_machina` as a dependency will confuse contributors, and quite some code can be removed.
> 
> 
> 
> 🍻

I totally agree! My goal was not to introduce a new dependency in the lib at the first place 👍🏻

**Comment by gcauchon** [comment]
> Also have a look at this tweet: https://twitter.com/davydog187/status/1274018846949736448

I actually never challenged choosing `ex_machina` at the first place, but reading thru this thread makes me realize I should have… It's on my list of many things to improve, thanks for sharing ❤️
