### ISSUE TITLE
Validation messages for nested embeds

### ISSUE THREAD

**Issue by daveli** [mathieuprog/polymorphic_embed#2]
👋 First of all cheers for making this library!

I'm currently experiencing some issues with validating nested embeds and hope ya can provide some insights. I have the following data-structure:

```
%{
  foo: %{
    bar: %{ <= Polymorphic embed
       __type__: "x",
      title: "test",
      images: %{ <= embeds_one
        large: "https://foo.bar/x.png",
        small: "https://foo.bar/x.png",
      }
    }
  }
}
```

Where the field title is required and so are the fields large and small under images.
With the current implementation it will return the correct validation error for the title field (e.g. required field) but will not show any validation errors for fields under images. Any ideas on how to resolve this?

**Comment by mathieuprog** [comment]
Hi there!

Could you try with the following branch?
```
{:polymorphic_embed,
  git: "git://github.com/mathieuprog/polymorphic_embed.git",
  branch: "nested_embeds_errors",
  override: true}
```

**Comment by daveli** [comment]
Hey! Awesome that seems to be working! 🎉
