### ISSUE TITLE
Option to change the `__type__` key

### ISSUE THREAD

**Issue by icehaunter** [mathieuprog/polymorphic_embed#23]
I like having the key to explicitly differentiate between the embeds. It works very nicely with TypeScript's discriminated unions on the frontend. But some other places in my system already use the `:type` key without the underscores. 

Is there a way to add a possibility to change the key? Thanks!

**Comment by mathieuprog** [comment]
Can you try using version 1.2.0 and let me know if that suits you? When will you be able to test it?
New option is `:type_field`.

Note that lists of polymorphic embeds are also supported now. Breaking change: you are now forced to set the `:on_replace` option (to `:update` for single embed and `:delete` for lists of embeds).
