### ISSUE TITLE
Primary key for many.

### ISSUE THREAD

**Issue by moonpeople** [mathieuprog/polymorphic_embed#33]
I try get id in polymorphic object, but it always nil.

```elixir
schema "presets" do
  field :name, :string
  field :show, :boolean, default: false
  belongs_to :user, User
  field :fields, {:array, PolymorphicEmbed},
    types: [
      string: StringField,
      text: TextField
    ],
    type_field: :type,
    on_type_not_found: :raise,
    on_replace: :delete

  timestamps()
end
```
  
StringField

```elixir
@primary_key {:id, :binary_id, autogenerate: true}
embedded_schema do
  field :title, :string
  field :type, :string
end
```

But no id when insert in DB

```elixir
{:ok,
 %Preset{
   __meta__: #Ecto.Schema.Metadata<:loaded, "presets">,
   fields: [
     %TextField{
       id: nil,
       title: "Sec text",
       type: nil
     },
     %StringField{
       id: nil,
       title: "Sec string",
       type: nil
     }
   ],
   id: 1,
   inserted_at: ~N[2021-01-14 21:47:41],
   name: "Second preset",
   show: false,
   updated_at: ~N[2021-01-14 21:47:41],
   user: #Ecto.Association.NotLoaded<association :user is not loaded>,
   user_id: 1
 }}
```

When i use embeds_many all ok.

Can you help me?

**Comment by mathieuprog** [comment]
Why do you need an ID for those embeds? Just curious

**Comment by moonpeople** [comment]
This is schema for template. I need this id for changes, if someone want update. And then this id will be use in other table for save values. I can do this field by Ecto.UUID. But i not understand why embeds_many create primary key by default, but polymorphic not. What for you write @primary_key false in your example, if delete this line id will be nil? I think that polymorphic must extends functionality, not narrow. But you did good job!

**Comment by mathieuprog** [comment]
> What for you write @primary_key false in your example

Because IDs are not supported now. But I should clarify that in the docs; I just never analyzed that part yet.

> I think that polymorphic must extends functionality,

Agreed but it must be coded and tested 😅

**Comment by mathieuprog** [comment]
Bro! Bro! IDs are supported for embeds. Note that lists have the setting `on_replace: :delete`, so I think any update on the list will create new IDs.

Share feedback if you can.
