### ISSUE TITLE
`put_polymorphic_embed` Support?

### ISSUE THREAD

**Issue by coladarci** [mathieuprog/polymorphic_embed#34]
We are extremely excited about this library and ran into a subtle issue for our application. 

While `cast_polymorphic_embed` works perfectly for us, we have a situation where we need to create a record out of an already cast embed. I.e we want to move the value from one persisted record to another record. 

I tried, as a work around, to use `Map.from_struct` and then re-cast the data, but the issue here is that the Struct that is exposed doesn't have the `__type__` field and our casting very much needs it as we can't infer the type since many sub-types share the same fields (don't ask :) )

I'm going to go down the path of using `get_polymorphic_type/3` and re-casting, though this isn't working, either, yet for reasons I haven't yet determined.

That said, I believe the correct answer to this is to implement `put_polymorphic_embed` so I can just drop in an existing value, somehow, instead of having to re-cast it. What do you think?

**Comment by coladarci** [comment]
For what it's worth, this is what happens when I try and use `PolymorphicEmbed.get_polymorphic_type`

```
PolymorphicEmbed.get_polymorphic_type(MyParentSchema, :value, my_persisted_value)
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.apply(%MyParentSchema{__meta__: #Ecto.Schema.Metadata<:loaded, "my_parent_schemas">, value: %MyParentSchema.SubField{unit: :lb}, :__schema__, [:type, :value])
        (polymorphic_embed 1.3.4) lib/polymorphic_embed.ex:297: PolymorphicEmbed.get_field_options/2
        (polymorphic_embed 1.3.4) lib/polymorphic_embed.ex:273: PolymorphicEmbed.get_polymorphic_type/3
```
I'm passing in the parent schema that holds the polymorphic field as the first arg, I'm passing the field name as an atom that holds the polymorphic embed and I'm passing the full cast value as the third param; I see that it's supposed to accept `module_or_struct` so I'm thinking that should work.

Any ideas? This would be a fine workaround for now..

**Comment by mathieuprog** [comment]
What happens if you use `put_change/3`?

**Comment by mathieuprog** [comment]
As I don't have feedback I'm closing this for now. Do not hesitate to come back if you have time to discuss further.
