### ISSUE TITLE
Type field not populated on cast

### ISSUE THREAD

**Issue by richthedev** [mathieuprog/polymorphic_embed#37]
Hi, I was trying to figure out why the type field is `nil` after using the `cast_polymorphic_embed` function. After reading the code I noticed the type field is only populated inside the `dump` ecto type implementation. Is there any reason why this is so?

This is the struct after an insert:
```
%PolymorphicEmbed.Reminder{
   __meta__: #Ecto.Schema.Metadata<:loaded, "reminders">,
   channel: %PolymorphicEmbed.Channel.SMS{
     country_code: 1,
     my_type_field: nil,
     number: "02/807.05.53"
   },
   date: ~U[2020-05-28 02:57:19Z],
   id: 1,
   inserted_at: ~N[2021-03-18 20:35:34],
   text: "This is an SMS reminder true",
   updated_at: ~N[2021-03-18 20:35:34]
 }
```

and this is the struct after "reloading" the data:
```
%PolymorphicEmbed.Reminder{
  __meta__: #Ecto.Schema.Metadata<:loaded, "reminders">,
  channel: %PolymorphicEmbed.Channel.SMS{
    country_code: 1,
    my_type_field: "sms",
    number: "02/807.05.53"
  },
  date: ~U[2020-05-28 02:57:19Z],
  id: 1,
  inserted_at: ~N[2021-03-18 20:35:34],
  text: "This is an SMS reminder true",
  updated_at: ~N[2021-03-18 20:35:34]
}
```

Notice how the `my_type_field` value only set when I load the data through `Repo.one` here.

**Comment by mathieuprog** [comment]
Actually you took as example the schema `PolymorphicEmbed.Channel.SMS` but there is no field `:my_type_field` there.
https://github.com/mathieuprog/polymorphic_embed/blob/v1.4.0/test/support/models/polymorphic/channel/sms.ex#L1

**Comment by mathieuprog** [comment]
I'll close this issue as I didn't receive a feedback. Feel free to re-open it if there are some updates.
