### ISSUE TITLE
non validation type

### ISSUE THREAD

**Issue by danil-chibrikov** [mathieuprog/polymorphic_embed#46]
Hey, there. I would like to use it by next case:
I need to check a field for the presence of some types, if the type is different or all is missing, don't validate and set an empty map by default. Is it possible?

I would like to see:
```
 schema "events" do
    field :meta, PolymorphicEmbed,
      types: [
        g: Goal
      ],
      on_replace: :update

    timestamps()
  end
  
%Event{
  meta: %Goal{
    assist: nil,
    player: nil,
    pre_assist: nil,
    team: nil
  },
  type: "g"
}

%Event{
  meta: %{},
  type: "blablabla"
}
```

I found this, but it blocks recording to the database
```
:on_type_not_found – specify whether to raise or add a changeset error if the embed's type cannot be inferred. Possible values are :raise and :changeset_error. By default, a changeset error "is invalid" is added.
```

In my world, I would like to use something like `on_type_not_found: :non_validation`

Maybe I don’t know something, but what other ideas?

**Comment by mathieuprog** [comment]
Hey. The type should be inside the embed. But I see that your type is in another field of your shema? `:type` should be inside `:meta`.

Now for your question, why does it need to be empty? Why is the type unknown in the system?

**Comment by danil-chibrikov** [comment]
@mathieuprog yes, I have type outside embedded. But I put it in embedded for validation. I expect there are types for which structure isn't needed, just default `%{}`

**Comment by mathieuprog** [comment]
Can you try v1.8.0?

Set option `:on_type_not_found` to `:nilify` for single embeds or `:ignore` for lists of embeds.

What do you think?

**Comment by danil-chibrikov** [comment]
Yes, it's what I need. Thanks for the quick response

**Comment by danil-chibrikov** [comment]
Sorry, but `do_load/3` return raise if I use not described type.

```
  schema "events" do
    field :type, :string

    field :meta, PolymorphicEmbed,
      types: [
        g: Goal
      ],
      on_type_not_found: :nilify,
      on_replace: :update

    timestamps()
  end

#Ecto.Changeset<
  action: nil,
  changes: %{type: "q"},
  errors: [],
  data: #Pluto.Models.Event<>,
  valid?: true
>

%Event{
   __meta__: #Ecto.Schema.Metadata<:loaded, "events">,
   id: 634,
   inserted_at: ~N[2021-12-20 10:58:09],
   meta: nil,
   type: "q",
   updated_at: ~N[2021-12-20 10:58:09]
 }
```

**Comment by mathieuprog** [comment]
Thank you. Why do we receive `%{}` instead of `nil`?
We have:
```elixir
def load(nil, _loader, _params), do: {:ok, nil}
```

**Comment by danil-chibrikov** [comment]
I think `%{}` better than `nil`

**Comment by mathieuprog** [comment]
But how do you have `%{}` ?

**Comment by danil-chibrikov** [comment]
Oh, sorry. It was my mistake with migration. I put `default: %{}`

**Comment by danil-chibrikov** [comment]
Still, I think that you need to put down the default value from the migration

**Comment by mathieuprog** [comment]
> Still, I think that you need to put down the default value from the migration

I didn't understand what you mean

**Comment by danil-chibrikov** [comment]
That's okay for flag :nilify

**Comment by danil-chibrikov** [comment]
Everything works well, thanks. I think you can close the Issue

**Comment by danil-chibrikov** [comment]
@mathieuprog I'm very sorry, but `:ignore` doesn't work.

```
** (UndefinedFunctionError) function :type_not_found.__struct__/0 is undefined (module :type_not_found is not available)
    :type_not_found.__struct__()
    (polymorphic_embed 1.8.0) lib/polymorphic_embed.ex:60: anonymous fn/4 in PolymorphicEmbed.cast_polymorphic_embed/3
    (polymorphic_embed 1.8.0) lib/polymorphic_embed.ex:164: PolymorphicEmbed.cast_polymorphic_embeds_one/5
```

I didn't find matching `:ignore` in `cast_polymorphic_embeds_one/5`

```
    case struct do
      :type_not_found when on_type_not_found == :raise ->
        raise_cannot_infer_type_from_data(params)

      :type_not_found when on_type_not_found == :changeset_error ->
        Ecto.Changeset.add_error(changeset, field, "is invalid")

      :type_not_found when on_type_not_found == :nilify ->
        Ecto.Changeset.put_change(changeset, field, nil)

      struct ->
        embed_changeset = changeset_fun.(struct, params)
```

**Comment by mathieuprog** [comment]
`:ignore` can only be used when you have a list of polymorphic embeds.

**Comment by mathieuprog** [comment]
What are you trying to do?

**Comment by danil-chibrikov** [comment]
I try to insert in database

schema
```
schema "events" do
  field :type, :string
  field :meta, PolymorphicEmbed,
    types: [
      g: Goal
    ],
    on_type_not_found: :ignore,
    on_replace: :update

  timestamps()
end
```

`App.Models.Event.changeset(%App.Models.Event{}, %{type: "asfasfg"}) |> App.Repo.insert`

After I get the error
```
** (UndefinedFunctionError) function :type_not_found.__struct__/0 is undefined (module :type_not_found is not available)
    :type_not_found.__struct__()
    (polymorphic_embed 1.8.0) lib/polymorphic_embed.ex:60: anonymous fn/4 in PolymorphicEmbed.cast_polymorphic_embed/3
    (polymorphic_embed 1.8.0) lib/polymorphic_embed.ex:164: PolymorphicEmbed.cast_polymorphic_embeds_one/5
```

**Comment by mathieuprog** [comment]
Why don't you use the option `:nilify`?

**Comment by danil-chibrikov** [comment]
Because I would like to get `%{}` instead of `nil`

**Comment by mathieuprog** [comment]
Why?

**Comment by danil-chibrikov** [comment]
I understand about `:nilify` type. It's normal!
I created this incident just to skip validation of unspecified types and set a default value for the field being validated.

I expect that a field `map` will have a default value `%{}`

**Comment by mathieuprog** [comment]
You also cannot set an `embeds_one` to an empty map `%{}` I think. The polymorphic type is working like embeds_one/embeds_many.

**Comment by danil-chibrikov** [comment]
Well, I'll use `:nilify` type for my case
I'm sorry to trouble you

**Comment by mathieuprog** [comment]
No problem. Just to clarify again, you see the polymorphic embed as a map of values, that's why you want to have `%{}`. But the idea is that the polymorphic embed is a dynamic embeds_one, which is a schema struct, so `%{}` doesn't make sense in that case. It's either the struct, or `nil`.
