### ISSUE TITLE
Support for a map fallback when type is not found

### ISSUE THREAD

**Issue by anirudhsama** [mathieuprog/polymorphic_embed#47]
Hi

I have an app where people can play game like Werewolf, Pictionary. Players can spin up a room and share a 4 letter code with their friends so that they can join the same room. The schema for this is as follows:

```elixir
schema "rooms" do
    field :code, :string
    field :game_id, :string
    field :completed_at, :utc_datetime
    field :data, :map

    timestamps()
  end
```

All this while, I was supporting simple games and didn't have much need for strict validation of what goes into the `data` column. But now, I'm coding up a Sudoku game where I want to validate the data that goes into the `data` column using `embedded_schemas`. Since there are lots of existing rows without existing `__type__` value in the data, is there a way to fallback to `:map` type? Perhaps this can be added as an additional option for `on_type_not_found`

**Comment by mathieuprog** [comment]
Hello. This seems hacky. The idea of the library is to allow dynamic embeds, and it gives you different ways to handle an error (invalid changeset, nilifying, raising, ...), but it doesn't allow to "bypass" the ecto type (and not treat it as an error), which is what you're asking.

You should maybe create a new embedded type, e.g. RawData, in which you have the :data map field. And you migrate all your map data by adding the appropriate __type__ field in them.
So I think the problem is easily solved, but you have this problem now only because you have all that existing data.
Another idea is to add a second field and have the map data as a fallback in your code, e.g. struct.data || struct.raw_data

**Comment by anirudhsama** [comment]
Thank you for the quick response and detailed feedback. Let me clarify my use case a bit more.

I want to use it for dynamic embeds as and when I add support for newer games and when I get time to update the older games. In the end it would look something like this:

```elixir
schema "rooms" do
    field :code, :string
    field :game_id, :string
    field :completed_at, :utc_datetime
    field :data, PolymorphicEmbed,
      types: [
        sudoku: SudokuGameData,
        crosswords: CrosswordsGameData,
        pictionary: PictionaryGameData
      ],
      on_type_not_found: :raise,
      on_replace: :update

    timestamps()
  end
```

But in the meanwhile, during the transition, it would be helpful if `data` behaved as it did previously i.e as a `map`. This way I don't have to change all the existing code that expects it to be a `map` and I can incrementally adopt dynamic embeds.


> You should maybe create a new embedded type, e.g. RawData, in which you have the :data map field.

If I define a RawData embed like so:

```elixir
defmodule RawData do
  embedded_schema do
    field :data, :map
  end
end

defmodule Room do
  schema "rooms" do
    field :code, :string
    field :game_id, :string
    field :completed_at, :utc_datetime

    field :data, PolymorphicEmbed,
      types: [
        sudoku: SudokuGameData,
        raw: RawData
      ],
      on_type_not_found: :raise,
      on_replace: :update

    timestamps()
  end
end
```

Then to access the data in games that don't support it, it would have to be accessed in this manner - `room.data.data` correct?. Also, how would it read existing rows and populate it? For a game like Pictionary, the `data` column has the following entry:

```json
{"words": ["cat", "umbrella", "phone", "forest"]}
```

For something like Werewolf:

```json
{"phase": "day", "player_role": {}}
```

Since there is no top level key called `data` in the above JSON, the `data` key in RawData will be `nil`. In order to support all the existing columns, I would have update the DB entries to something like:

```json
{"data": {"words": ["cat", "umbrella", "phone", "forest"]}}
```

```json
{"data": {"phase": "day", "player_role": {}}}
```

Apart from DB entries, I would also have to update the code where it is being reference as `room.data` to `room.data.data`.

Therefore, as a way to incrementally adopt dynamic embeds, it would be much easier if `room.data` could fallback to Ecto `map` type when there is no type definition found.

**Comment by mathieuprog** [comment]
> `room.data.data`

I would name the type to `:other` (makes more sense to have sudoku, pictionary, etc. and "other" or miscellaneous), and I would name the embedded_schema `OtherGameData` or something similar, with a field named `:map` which is of type `:map`. Then you have `room.data.map`.

I understand that there is a lot of work to refactor and introduce the new generic type for the other games, but I don't feel like we should add code to fallback to the source data without type... Not only do we have to ignore the code logic when casting, but also the code logic when loading from the database. The use case is too specific, and solvable in userland.

Also, maybe the second idea to add an additional column will allow you to transition easier.

**Comment by anirudhsama** [comment]
Alright! Thanks for your suggestion 👍
