### ISSUE TITLE
`traverse_errors/2` blows up when the polymorphic embed is valid

### ISSUE THREAD

**Issue by jerelmiller** [mathieuprog/polymorphic_embed#48]
Hey there! Thanks so much for this library! I've found great value in it!

I am using `PolymorphicEmbed.traverse_errors/2` as a replacement for `Ecto.Changeset.traverse_errors/2` and noticed that the function blows on a `FunctionClauseError` if the polymorphic embed is valid. I see that if the embedded changeset is valid, it [applies the changes](https://github.com/mathieuprog/polymorphic_embed/blob/6a5b1fa2ba4c5c2258363ecc9976e38ee7dce097/lib/polymorphic_embed.ex#L173-L177), which results in that field converted from a changeset to a struct. When traversing errors, it appears that when merging the polymorphic keys, it attempts to call [`traverse_errors/2` again](https://github.com/mathieuprog/polymorphic_embed/blob/6a5b1fa2ba4c5c2258363ecc9976e38ee7dce097/lib/polymorphic_embed.ex#L374-L379), but since the change is now a struct instead of a changeset, `traverse_errors/2` can't match, resulting in a `FunctionClauseError`.

**Comment by thojanssens** [comment]
Hello. Can I see the error? I'll look i to it. Do you think you'd be able to add a failing test?

**Comment by mathieuprog** [comment]
Hello. Can you paste the error? I'll look into it. Would you be able to add a failing test?

**Comment by mathieuprog** [comment]
Hello, it's pretty clear:) first thing to do is to add a failing test. I'll work on that when I have time in the next few days, feel free to add one if you have time, otherwise I'll be on it some time later. Once we have a failing test, it will be solved pretty much immediately.

**Comment by jerelmiller** [comment]
Perfect! Hopefully I get some free time tomorrow to help out here! Thanks for getting back so quick!

**Comment by mathieuprog** [comment]
Fixed  in PRhttps://github.com/mathieuprog/polymorphic_embed/pull/50
