### ISSUE TITLE
Trying to get a list of types for a field 

### ISSUE THREAD

**Issue by ghost** [mathieuprog/polymorphic_embed#56]
In the frontend, I would like to present the user the possibility to choose the type and then the correct polymorphic form will appear.

To get a list of availble types of a field, I was thinking about: https://hexdocs.pm/polymorphic_embed/PolymorphicEmbed.html#types/2

But I am getting an error, because the atoms does not exist:

```
iex(7)> PolymorphicEmbed.types(MySchema, :a_poly_field)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("catalog", :utf8)
    (polymorphic_embed 1.9.0) lib/polymorphic_embed.ex:344: anonymous fn/1 in PolymorphicEmbed.types/2
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
```

Is there a way around this? I understand `String.to_atom` is dangerous, is there an alternative?

Thank you

**Comment by carlotm** [comment]
pfff because I was mispelling it. Sorry for the noise :man_facepalming:
