### ISSUE TITLE
Unable to use it with ex_machina?

### ISSUE THREAD

**Issue by x-ji** [mathieuprog/polymorphic_embed#57]
It seems that I'm unable to use it with ex_machina. Not sure if I'm doing something wrong here. I get the error

```
 ** (RuntimeError) Elixir.PolymorphicEmbed must not be casted using Ecto.Changeset.cast/4, use Elixir.PolymorphicEmbed.cast_polymorphic_embed/2 instead.
```

so it seems that `ex_machina` by default tries to run `cast`?

Example:

```
  def entry_factory do
    %Entry{
      # ...
      data: %{
        field_1: 123,
        field_2: 123,
        field_3: 123
      }
    }
  end
```

Schema:

```
  schema "entries" do
    # ...

    field :data, PolymorphicEmbed,
      types: @types_map,
      type_field: :type,
      on_type_not_found: :raise,
      on_replace: :update
  end
```

Trying to use a call to `build/1` at the `:data` key seems to yield the same result.

Stacktrace of the error:

```
     code: entry = insert(:entry)
     stacktrace:
       (polymorphic_embed 2.0.0) lib/polymorphic_embed.ex:247: PolymorphicEmbed.cast/2
       (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:72: ExMachina.EctoStrategy.cast_value/3
       (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:58: anonymous fn/2 in ExMachina.EctoStrategy.cast_all_fields/1
       (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:49: ExMachina.EctoStrategy.cast/1
       (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:25: ExMachina.EctoStrategy.handle_insert/2
```

(BTW, I don't like `ex_machina` very much, though the codebase that I'm working with already uses it.)

**Comment by mathieuprog** [comment]
See https://github.com/thoughtbot/ex_machina/issues/407

Also https://twitter.com/davydog187/status/1274018846949736448

**Comment by x-ji** [comment]
Thanks for pointing to the discussion. I wasn't able to find it by searching through the issues, though I see I should be able to find it by also including the open PRs.

> Also https://twitter.com/davydog187/status/1274018846949736448

Yes, I've seen this in the other `ex_machina` related issue and I absolutely agree. As I wrote above:

> (BTW, I don't like ex_machina very much, though the codebase that I'm working with already uses it.)

**Comment by mathieuprog** [comment]
Ah I missed that, I was on my phone responding too quickly:)
But yeah... you figured out the problem by yourself, `ex_machina` indeed calls `cast`. The only way is to add some dirty code as shown in the PR or help `ex_machina` maintainer to come up with a generic solution.

**Comment by maxsalven** [comment]
> FWIW I worked around this by using ex_machina's build function and Repo.insert!. Avoiding insert seems to do the trick for me at least.

Thanks for that! Looks like you can then define a [custom strategy](https://hexdocs.pm/ex_machina/readme.html#custom-strategies) in ExMachina:

```elixir
defmodule MyApp.Factory.PolymorphicEmbedStrategy do
  use ExMachina.Strategy, function_name: :insert_polymorphic

  def handle_insert_polymorphic(record, _opts) do
    MyApp.Repo.insert!(record)
  end
end
```

and then in your tests:
```elixir
insert_polymorphic(:entry)
```
