### ISSUE TITLE
Could not infer polymorphic embed on the README example

### ISSUE THREAD

**Issue by bartosjiri** [mathieuprog/polymorphic_embed#61]
Hey all, thank you for the work on this library!

I've been trying to implement it using the [README example](https://github.com/mathieuprog/polymorphic_embed#usage), but without any success so far, always resulting in the following error:
- could not infer polymorphic embed from data %{`<embedded-data>`}

I have created a minimum reproduction repository, explaining the setup and individual reproduction steps, available here:
- https://github.com/bartosjiri/ecto-polymorphic-embeds-infer-issue

*Note: I am fairly new to Elixir/Phoenix, so there might be something very obvious that I am missing...*

Thank you for your time in advance!

**Comment by mathieuprog** [comment]
there's missing a __type__ field in the map no?

**Comment by bartosjiri** [comment]
> there's missing a **type** field in the map no?

Indeed!
Silly me, thanks for the quick response ♥
