### ISSUE TITLE
How to define the tables/migrations?

### ISSUE THREAD

**Issue by cvkmohan** [mathieuprog/polymorphic_embed#62]
Thanks for the library. This is not really an issue with the library but a question that I have. Did not know where to put it - hence made it an issue. 
The README provided clear details on how to define the schema. I want to know how to define the migration for the table `reminders`. What does `polymorphic_embded` expect? Two fields `type` and `channel_id` without referential integrity constraints? Or two fields `sms_id` and `email_id`?

**Comment by mathieuprog** [comment]
This has been added in the readme file:
> In your migration file [...]

Is this clear now?

**Comment by cvkmohan** [comment]
Thanks for the prompt response. Yes, the implementation is very clear now.

**Comment by mathieuprog** [comment]
Note that it is the same as working with the Ecto embeds. That's why it was not documented.
In your database you'll have a JSONB field.

**Comment by cvkmohan** [comment]
I agree. On hindsight you are right. But at that moment, I could not fathom it correctly.
