### ISSUE TITLE
Casting Runtime errors

### ISSUE THREAD

**Issue by tuomohopia** [mathieuprog/polymorphic_embed#8]
When casting a data structure in Changesets that the library does not expect, it will trigger a runtime error such as

```elixir
** (RuntimeError) could not infer polymorphic embed from data %{}
```

Ideally, I'd rather have this as an `:error` as would be produced by `Ecto.Type.cast/1`. This way, I could get the error back to the Changeset instead of having to defensively try to `rescue` errors with Changeset casting.

Could this be improved at library level, or am I somehow using this wrong currently?

**Comment by mathieuprog** [comment]
I think it depends whether the error is caused by a bug in the code, or invalid user input.

User input will go through a set of Changeset validations and any errors will be added to the Changeset and generally displayed in a form, allowing the user to correct his input. However, when there's a bug in your code, in Erlang/Elixir it's normal to let the application crash; you should then notice the bug and fix it.

If we add an error to the Changeset, and the error was caused by some erroneous code, we might miss that bug.

I guess in your case, this was a bug in the code?

**Comment by tuomohopia** [comment]
I'll check tomorrow again if it was my own code but from what I understand this is a casting error in the changesets. 

So `cast` produces the changeset from the parameters. We cannot run changeset validations before casting the data right? Currently, I'm casting external parameters to the polymorphic embed with `cast`. And this triggers that runtime error when the external parameters are not what the library expects for determining which polymorphic type to use.

**Comment by mathieuprog** [comment]
If the library doesn't know which type to use, it is an error in the code. Typically a hidden input `"__type__"` would be missing.

**Comment by tuomohopia** [comment]
Right, so that's what I got a problem with. I'm building an API where the user can supply anything they want. With this library's current approach, I'd have to write a pre-validation outside of Ecto Changesets before attempting to cast the external parameters to the polymorphic embed. Or optionally, build a defensive rescue for a failed Changeset cast. 

I feel this is not how Ecto custom types should work. The Changesets are built for validating external data, and should generally not trigger a runtime error on receiving unexpected data. It should simply fail to cast it, which would propagate back to the Changeset as a `:cast` error.

The custom `Ecto.Type.cast/1` callback return values reflect this: https://github.com/elixir-ecto/ecto/blob/266e4fc2313c43f10276ac45e59f72c768e7ecb9/lib/ecto/type.ex#L229

If we expect that `cast/1` would cause a runtime error upon unexpected data, it would be annotated with a bang `!` instead, as in `cast!/1`.

**Comment by mathieuprog** [comment]
This library's `cast` also may return a tuple `{:error, changeset}` on error https://github.com/mathieuprog/polymorphic_embed/blob/master/lib/polymorphic_embed/custom_type.ex#L43

> If we expect that cast/1 would cause a runtime error upon unexpected data, it would be annotated with a bang ! instead, as in cast!/1.

Not true. Take a random example, `put_assoc`: if you pass it a wrong field as argument, it will trigger an error (`KeyError`), although it has no bang `!`. A function without a bang doesn't necessarily mean it won't raise an error.

> the user can supply anything they want

What kind of inputs do you provide to the user? How does the type get determined?

**Comment by tuomohopia** [comment]
I don't believe it's the same thing with `put_assoc`. Because you do not pass external parameters to it directly. Instead, it takes a Changeset and the name of the field, which is supplied by the programmer, not the user. You would've already constructed the Changeset before calling it. Therefore, if it caused a runtime error that would clearly be an error in the application code.

Whereas if the `cast` fails, there is that callback return type for indicating the failure, handled by Ecto. I don't see why it should also optionally raise errors in some cases. 

In my case, as my users are my API consumers, I have no control over what they supply as parameters in their endpoint calls. I use Changesets to validate the supplied parameters. If they supply faulty parameters, I'd like to give them back the Changeset errors indicating which cast or validation failed, instead of it simply crashing.

**Comment by mathieuprog** [comment]
Thank you I understand your argument. Let me do some research on the topic and ask the community, I'll get back to you soon.

**Comment by tuomohopia** [comment]
Thanks for spending time looking into it!

**Comment by mathieuprog** [comment]
Thank you for raising this question. I'd like to add an option to make it optionally raise, but to default the option to a changeset error as you suggested.
If you have any idea of the error key and error message to add in the changeset, and even option name and value for raising, let me know:)

**Comment by tuomohopia** [comment]
Awesome, thanks!

I feel the current error message is nicely descriptive. I mean
```elixir
"could not infer polymorphic embed from data #{inspect(attrs)}"
```
As for the key, maybe something like `:poly_inference` or something to indicate it's an error determining which embedded schema to pick would work?

**Comment by mathieuprog** [comment]
This is an error message for programmers. Changeset errors are for users (as "can't be black", ""should be at least %{count} characters", etc.).

**Comment by mathieuprog** [comment]
An option `:on_type_not_found` has been added. By default, a changeset error "is invalid" will be added to the changeset.
Let me know if you think this can be improved.

Note that the API has changed in the meanwhile for defining and casting your dynamic embeds, check the Readme.

**Comment by tuomohopia** [comment]
Thanks a lot, I appreciate you spending your personal time to produce a solution to this!
