### ISSUE TITLE
Plans for this Library

### ISSUE THREAD

**Issue by Miradorn** [mathieuprog/polymorphic_embed#87]
Hi there, especially @mathieuprog.

First thanks for this great Library, it has helped us a lot and is a joy to use ❤️ 

It seems though that you might not had time or reason to work on it for some time and there are some bugs we've been running into, which even have open MRs (e.g. fixing compile time dependencies).
Therefore I wanted to ask if you're still interested in maintaining the library in the future or if we can find a way to keep it updated.

Again: thanks for all the work, and just to make sure: this is not intended to blame you for not working at the library at all, I completely understand that you've been doing this on your own time and there are good reasons to not continue to do it, I only want to try to find a way to keep the project up to date.

**Comment by hickscorp** [comment]
Bump. Are there plans to either maintain or maybe transfer ownership?

**Comment by ElijahBrandyberry** [comment]
We have used this library extensively, and it has proved very useful!  I would be happy to contribute to maintaining this if this can become a community effort.

**Comment by mathieuprog** [comment]
Hello. The most blocking PRs have been addressed.
