### ISSUE TITLE
`polymorphic_embeds_many` seems unfinished.

### ISSUE THREAD

**Issue by hickscorp** [mathieuprog/polymorphic_embed#89]
I've been using this lib for a long time, but just ran across use cases as it's the first time I try `polymorphic_embeds_many`.
It seems to me that there's missing functionality.

Consider a schema having two possible types of embeds in a `polymorphic_embeds_many` "`things`" field. How do you:
- Add to the list, while leveraging polymorphism (Ideally using the `type` field in `attrs` to use the right module to call `changeset/2` on)?
- Remove to the list ...?
- Chain calls... Eg `model |> add_thing_to_things(%{...}) |> add_thing_to_things(%{...})` ...?

**Comment by mathieuprog** [comment]
Could you mention how you perform all of the mentioned operations using `embeds_many`? Then we can check if any of these is not supported by the polymorphic version from this lib.
