### ISSUE TITLE
Missing actual usage example

### ISSUE THREAD

**Issue by BlueHotDog** [mathieuprog/polymorphic_embed#9]
Hi, trying to see if this library is for me, but just couldnt figure out how to actually make it work.
Is there a phoenix example using this? 
The current example is tied to a form, but the whole Context part is missing.

**Comment by mathieuprog** [comment]
In the context, you just call the changeset function and pass the params, as usual. There is northing particular or unusual.
In the case of the example in the docs:

```
def create_reminder(attrs) do
  %Reminder{}
  |> Reminder.changeset(attrs)
  |> Repo.insert()
end
```

The polymorphic type is included in the `attrs` and the library will store/load the right embed.

**Comment by mathieuprog** [comment]
If you need any further assistance, don't hesitate to ask in this thread. I'll marked this issue as closed now.

**Comment by leohoe** [comment]
This usage example doesn't work for me - any time I try to run the changeset on just a struct, I get errors like this:
`iex(13)> %Atlas2.Sections.Section{} |> MyApp.Sections.Section.changeset(my_section) |> MyApp.Repo.insert()`
`** (KeyError) key :data not found in: %MyApp.Sections.Section{__meta__: #Ecto.Schema.Metadata<:built, "sections">, content: nil, id: nil, inserted_at: nil, updated_at: nil}
    (polymorphic_embed 3.0.1) lib/polymorphic_embed.ex:59: PolymorphicEmbed.cast_polymorphic_embed/3`

**Comment by leohoe** [comment]
Ah, wait, I found the issue - since `:content` was the only field, my changeset function looked like this:

```elixir
  def changeset(section, attrs) do
    section
    |> cast_polymorphic_embed(:content, required: true)
  end
```

It seems that without a prior cast(), cast_polymorphic_embed runs into problems.
The error disappeared when I added a cast() without actually casting any fields, like so:

```elixir

  def changeset(section, attrs) do
    section
    |> cast(attrs, [])
    |> cast_polymorphic_embed(:content, required: true)
    |> validate_required([])
  end
```

**Comment by mathieuprog** [comment]
@leohoe I reopened and I'll add my comment about your observation tomorrow

**Comment by mathieuprog** [comment]
@leohoe I spent an hour trying to solve that problem thinking there was a limitation in the library, but actually this is normal. You may see that `Ecto.Changeset.cast_embed/3` also only accepts a changeset as first argument, and if you pass anything else, you'll get some cryptic error.
However I raise now and added an dev-friendly error message in case anything else is passed (than a changeset) as first argument.
