### ISSUE TITLE
support Phoenix.HTML 4.0

### ISSUE THREAD

**Issue by woylie** [mathieuprog/polymorphic_embed#91]
This library needs to be updated for Phoenix.HTML 4.0. (edit: opened #93 )

**Comment by gaiabeatrice** [comment]
Hello! Thank you so much for the library!
I see that the work to support Phoenix HTML 4.0 was done (thank you!)! Do you have any news on when/if it is going to be released?

**Comment by egeersoz** [comment]
Hi @mathieuprog, possible to merge the linked PR?
